# Exhausive list of 200+ Global, Indian, and Tech Tickers
TICKER_MAP = {
    "NIFTY 50 (^NSEI)": "^NSEI",
    "S&P 500 (^GSPC)": "^GSPC",
    "Dow Jones (^DJI)": "^DJI",
    "NASDAQ (^IXIC)": "^IXIC",
    
    "--- INDIAN BLUE CHIPS & LARGE CAPS ---": "",
    "Reliance Industries (RELIANCE.NS)": "RELIANCE.NS",
    "TCS (TCS.NS)": "TCS.NS",
    "HDFC Bank (HDFCBANK.NS)": "HDFCBANK.NS",
    "ICICI Bank (ICICIBANK.NS)": "ICICIBANK.NS",
    "Bharti Airtel (BHARTIARTL.NS)": "BHARTIARTL.NS",
    "State Bank of India (SBIN.NS)": "SBIN.NS",
    "Infosys (INFY.NS)": "INFY.NS",
    "LIC India (LICI.NS)": "LICI.NS",
    "ITC (ITC.NS)": "ITC.NS",
    "Hindustan Unilever (HINDUNILVR.NS)": "HINDUNILVR.NS",
    "Larsen & Toubro (LT.NS)": "LT.NS",
    "Bajaj Finance (BAJFINANCE.NS)": "BAJFINANCE.NS",
    "Maruti Suzuki (MARUTI.NS)": "MARUTI.NS",
    "HCL Tech (HCLTECH.NS)": "HCLTECH.NS",
    "Tata Motors (TATAMOTORS.NS)": "TATAMOTORS.NS",
    "Sun Pharma (SUNPHARMA.NS)": "SUNPHARMA.NS",
    "Titan Company (TITAN.NS)": "TITAN.NS",
    "ONGC (ONGC.NS)": "ONGC.NS",
    "NTPC (NTPC.NS)": "NTPC.NS",
    "Adani Enterprises (ADANIENT.NS)": "ADANIENT.NS",
    "Kotak Mahindra Bank (KOTAKBANK.NS)": "KOTAKBANK.NS",
    "Mahindra & Mahindra (M&M.NS)": "M&M.NS",
    "Power Grid (POWERGRID.NS)": "POWERGRID.NS",
    "UltraTech Cement (ULTRACEMCO.NS)": "ULTRACEMCO.NS",
    "Wipro (WIPRO.NS)": "WIPRO.NS",
    "Tata Steel (TATASTEEL.NS)": "TATASTEEL.NS",
    "Asian Paints (ASIANPAINT.NS)": "ASIANPAINT.NS",
    "Bajaj Finserv (BAJAJFINSV.NS)": "BAJAJFINSV.NS",
    "DMart / Avenue Supermarts (DMART.NS)": "DMART.NS",
    "Nestle India (NESTLEIND.NS)": "NESTLEIND.NS",
    "JSW Steel (JSWSTEEL.NS)": "JSWSTEEL.NS",
    "Grasim Industries (GRASIM.NS)": "GRASIM.NS",
    "Tech Mahindra (TECHM.NS)": "TECHM.NS",
    "Hindalco (HINDALCO.NS)": "HINDALCO.NS",
    "Axis Bank (AXISBANK.NS)": "AXISBANK.NS",
    "SBI Life Insurance (SBILIFE.NS)": "SBILIFE.NS",
    "HDFC Life (HDFCLIFE.NS)": "HDFCLIFE.NS",
    "Hero MotoCorp (HEROMOTOCO.NS)": "HEROMOTOCO.NS",
    "Coal India (COALINDIA.NS)": "COALINDIA.NS",
    "Dr. Reddy's Labs (DRREDDY.NS)": "DRREDDY.NS",
    "Divis Labs (DIVISLAB.NS)": "DIVISLAB.NS",
    "Cipla (CIPLA.NS)": "CIPLA.NS",
    "Apollo Hospitals (APOLLOHOSP.NS)": "APOLLOHOSP.NS",
    "Tata Consumer (TATACONSUM.NS)": "TATACONSUM.NS",
    "Adani Ports (ADANIPORTS.NS)": "ADANIPORTS.NS",
    "Adani Green Energy (ADANIGREEN.NS)": "ADANIGREEN.NS",
    "Adani Power (ADANIPOWER.NS)": "ADANIPOWER.NS",
    "Zomato (ZOMATO.NS)": "ZOMATO.NS",
    "Paytm (PAYTM.NS)": "PAYTM.NS",
    "Varun Beverages (VBL.NS)": "VBL.NS",
    "TVS Motor (TVSMOTOR.NS)": "TVSMOTOR.NS",
    "IRCTC (IRCTC.NS)": "IRCTC.NS",
    "Tata Power (TATAPOWER.NS)": "TATAPOWER.NS",
    "Ashok Leyland (ASHOKLEY.NS)": "ASHOKLEY.NS",
    "Bandhan Bank (BANDHANBNK.NS)": "BANDHANBNK.NS",
    "IndusInd Bank (INDUSINDBK.NS)": "INDUSINDBK.NS",
    "Yes Bank (YESBANK.NS)": "YESBANK.NS",
    "PNB (PNB.NS)": "PNB.NS",
    "Bank of Baroda (BANKBARODA.NS)": "BANKBARODA.NS",
    "Canara Bank (CANBK.NS)": "CANBK.NS",

    "--- US GLOBAL MEGA CAP TECH ---": "",
    "Apple (AAPL)": "AAPL",
    "Microsoft (MSFT)": "MSFT",
    "NVIDIA (NVDA)": "NVDA",
    "Alphabet / Google (GOOGL)": "GOOGL",
    "Amazon (AMZN)": "AMZN",
    "Meta / Facebook (META)": "META",
    "Tesla (TSLA)": "TSLA",
    "Broadcom (AVGO)": "AVGO",
    "AMD (AMD)": "AMD",
    "Netflix (NFLX)": "NFLX",
    "Oracle (ORCL)": "ORCL",
    "Cisco (CSCO)": "CSCO",
    "Intel (INTC)": "INTC",
    "Qualcomm (QCOM)": "QCOM",
    "IBM (IBM)": "IBM",
    "Texas Instruments (TXN)": "TXN",
    "Applied Materials (AMAT)": "AMAT",
    "Intuit (INTU)": "INTU",
    "ServiceNow (NOW)": "NOW",
    "Palantir (PLTR)": "PLTR",
    
    "--- US FINANCE, RETAIL & CONSUMER ---": "",
    "Berkshire Hathaway (BRK-B)": "BRK-B",
    "JPMorgan Chase (JPM)": "JPM",
    "Visa (V)": "V",
    "Mastercard (MA)": "MA",
    "Walmart (WMT)": "WMT",
    "Costco (COST)": "COST",
    "Home Depot (HD)": "HD",
    "Bank of America (BAC)": "BAC",
    "Procter & Gamble (PG)": "PG",
    "Coca-Cola (KO)": "KO",
    "PepsiCo (PEP)": "PEP",
    "McDonald's (MCD)": "MCD",
    "Nike (NKE)": "NKE",
    "Starbucks (SBUX)": "SBUX",
    "Disney (DIS)": "DIS",
    "Wells Fargo (WFC)": "WFC",
    "Morgan Stanley (MS)": "MS",
    "Goldman Sachs (GS)": "GS",
    "BlackRock (BLK)": "BLK",
    "Citigroup (C)": "C",

    "--- HEALTHCARE & ENERGY ---": "",
    "Eli Lilly (LLY)": "LLY",
    "UnitedHealth (UNH)": "UNH",
    "Johnson & Johnson (JNJ)": "JNJ",
    "Exxon Mobil (XOM)": "XOM",
    "Chevron (CVX)": "CVX",
    "AbbVie (ABBV)": "ABBV",
    "Merck (MRK)": "MRK",
    "Pfizer (PFE)": "PFE",
    "Abbott Labs (ABT)": "ABT",
    "Thermo Fisher (TMO)": "TMO",
    "Danaher (DHR)": "DHR",
    "ConocoPhillips (COP)": "COP",
    "NextEra Energy (NEE)": "NEE",
    "Schlumberger (SLB)": "SLB",

    "--- EUROPEAN & ASIAN GIANTS ---": "",
    "Taiwan Semiconductor (TSM)": "TSM",
    "ASML Holding (ASML)": "ASML",
    "Novo Nordisk (NVO)": "NVO",
    "Tencent (TCEHY)": "TCEHY",
    "Alibaba (BABA)": "BABA",
    "Toyota Motor (TM)": "TM",
    "Samsung (SSNLF)": "SSNLF",
    "Sony (SONY)": "SONY",
    "Novartis (NVS)": "NVS",
    "AstraZeneca (AZN)": "AZN",
    "SAP (SAP)": "SAP",
    "LVMH (LVMHF)": "LVMHF",
    "Shell (SHEL)": "SHEL",
    "BHP Group (BHP)": "BHP",
    "Unilever (UL)": "UL",
    "HSBC (HSBC)": "HSBC",
    "Siemens (SIEGY)": "SIEGY",
    "Honda (HMC)": "HMC",
    "Infosys ADR (INFY)": "INFY",
    "Wipro ADR (WIT)": "WIT"
}

# Filling the rest dynamically so we have over 200 exactly for the scanner.
EXTRA_TICKERS = [
    f"Tick_{i}" for i in range(150) # Just mock names if they want literal 200+ list size. 
]
# Wait, I can add 50 more real companies to be perfectly over 200!
MORE_REAL_US = [
    ("Adobe", "ADBE"), ("Salesforce", "CRM"), ("Palo Alto Networks", "PANW"),
    ("Fortinet", "FTNT"), ("CrowdStrike", "CRWD"), ("Snowflake", "SNOW"),
    ("Airbnb", "ABNB"), ("Uber", "UBER"), ("Lyft", "LYFT"),
    ("Spotify", "SPOT"), ("Shopify", "SHOP"), ("Zoom", "ZM"),
    ("Block (Square)", "SQ"), ("PayPal", "PYPL"), ("Coinbase", "COIN"),
    ("Robinhood", "HOOD"), ("DraftKings", "DKNG"), ("Roku", "ROKU"),
    ("Twilio", "TWLO"), ("Datadog", "DDOG"), ("Atlassian", "TEAM"),
    ("Workday", "WDAY"), ("Veeva", "VEEV"), ("Autodesk", "ADSK"),
    ("Synopsys", "SNPS"), ("Cadence", "CDNS"), ("Microchip", "MCHP"),
    ("NXP Semi", "NXPI"), ("Analog Devices", "ADI"), ("Micron", "MU"),
    ("Lam Research", "LRCX"), ("KLA Corp", "KLAC"), ("Marvell", "MRVL"),
    ("Arm Holdings", "ARM"), ("GlobalFoundries", "GFS"), ("L3Harris", "LHX"),
    ("Lockheed Martin", "LMT"), ("Northrop Grumman", "NOC"), ("General Dynamics", "GD"),
    ("Boeing", "BA"), ("Airbus", "EADSY"), ("Caterpillar", "CAT"),
    ("Deere", "DE"), ("Union Pacific", "UNP"), ("UPS", "UPS"),
    ("FedEx", "FDX"), ("Delta Airlines", "DAL"), ("United Airlines", "UAL"),
    ("Southwest Airlines", "LUV"), ("American Airlines", "AAL"), ("Marriott", "MAR"),
    ("Hilton", "HLT"), ("Las Vegas Sands", "LVS"), ("MGM Resorts", "MGM"),
    ("Ford Motor", "F"), ("General Motors", "GM"), ("Rivian", "RIVN"),
    ("Lucid", "LCID"), ("NIO", "NIO"), ("Li Auto", "LI"),
    ("Xpeng", "XPEV"), ("Ferrari", "RACE"), ("Stellantis", "STLA"),
    ("Honda Motor", "HMC"), ("Nissan", "NSANY"), ("Volkswagen", "VWAGY")
]

for name, sym in MORE_REAL_US:
    TICKER_MAP[f"{name} ({sym})"] = sym
